---
title: "Insertion Model vignette"
output: BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{WeightInsertModels}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


## Dependencies
```{r}
suppressPackageStartupMessages({
    #remotes::install_github("Jiayi-Wang-Joey/WeightInsertModels")
    library(WeightInsertModels)
    library(rtracklayer)
    library(BSgenome.Hsapiens.UCSC.hg38)
})
```

## Data loading

To generate the motif activity scores, we need the following inputs:

- Original peak-level count matrix as `SummarizedExperiment`

```{r}
m <- "GATA1"
se <- readRDS(paste0("/mnt/plger/jwang/data/dat/01-total/total-",m,".rds"))
assay(se)[1:5,1:5]
```


- ATAC-seq fragments as a list:
```{r}
atacFrag <- readRDS(paste0("/mnt/plger/jwang/data/dat/00-frg/",m,".rds"))
head(atacFrag)
```

- motifRanges as `GRanges` object
```{r}
motifRanges <- readRDS(paste0("/mnt/plger/plger/DTFAB/fullFrags/",
          m,"/runATAC_results/others/pmoi.rds"))
```



- peakRanges

```{r}
peakRanges <- import("/mnt/plger/plger/DTFAB/fullFrags/GATA1/peaks/GATA1.bed.gz")
genome <- BSgenome.Hsapiens.UCSC.hg38
```

## Get motif activity score
```{r}
insCounts <- getWeightedInsertions(atacFrag, peakRanges, motifRanges, 
    genome=genome, subSample=1e5)
#mm <- getInsertionProfiles(atacFrag, motifRanges)
mi <- genomicRangesMapping(peakRanges, motifRanges, 
    byCols="motif_id", scoreCol="score", 
    type="any", aggregationFun=function(x){s <- fifelse(sum(x)>0, TRUE,FALSE)})

dev <- computeDeviationsWeighted(assays(insCounts$insertioncounts)$weighted_counts, 
    mi, insCounts$bgcounts)
```


### Apply limma on z-score
```{r}
x <- dev$z
group_id <- ifelse(grepl("CTRL", colnames(x), ignore.case = TRUE), "A", "B")
group_id <- relevel(factor(group_id), ref = "A")
design <- model.matrix(~ group_id)

fit <- eBayes(lmFit(x, design))
res <- topTable(fit, n = Inf, sort.by = "none")
res$name <- rownames(res)
res <- res[order(res$P.Value, -abs(res$logFC)),]
res$rank <- seq_len(nrow(res))
```

